id: CVE-2024-5708-js_composer-23ff12f0-eb9d-4bb3-8db0-0e794c0f0594

info:
  name: >
    WPBakery <= 7.7 - Authenticated (Author+) Stored Cross-Site Scripting
  author: topscoder
  severity: low
  description: >
    The WPBakery Visual Composer plugin for WordPress is vulnerable to Stored Cross-Site Scripting via the ‘link’ parameter in all versions up to, and including, 7.7 due to insufficient input sanitization and output escaping. This makes it possible for authenticated attackers, with Author-level access and above, and with post permissions granted by an Administrator, to inject arbitrary web scripts in pages that will execute whenever a user accesses an injected page.
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/23ff12f0-eb9d-4bb3-8db0-0e794c0f0594?source=api-prod
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:L/I:L/A:N
    cvss-score: 6.4
    cve-id: CVE-2024-5708
  metadata:
    fofa-query: "wp-content/plugins/js_composer/"
    google-query: inurl:"/wp-content/plugins/js_composer/"
    shodan-query: 'http.html:"wp-content/plugins/js_composer/"'
  tags: cve,wordpress,wp-plugin,js_composer,low,production

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/js_composer/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "js_composer"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 7.7')