id: CVE-2024-5212-td_composer-db95415a-5354-498b-8368-58c47d9948de

info:
  name: >
    tagDiv Composer <= 5.0 - Reflected Cross-Site Scripting via envato_code[]
  author: topscoder
  severity: medium
  description: >
    The tagDiv Composer plugin for WordPress is vulnerable to Reflected Cross-Site Scripting via the ‘envato_code[]’ parameter in all versions up to, and including, 5.0 due to insufficient input sanitization and output escaping within the on_ajax_register_forum_user function. This makes it possible for unauthenticated attackers to inject arbitrary web scripts in pages that execute if they can successfully trick a user into performing an action such as clicking on a link.
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/db95415a-5354-498b-8368-58c47d9948de?source=api-prod
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N
    cvss-score: 6.1
    cve-id: CVE-2024-5212
  metadata:
    fofa-query: "wp-content/plugins/td-composer/"
    google-query: inurl:"/wp-content/plugins/td-composer/"
    shodan-query: 'http.html:"wp-content/plugins/td-composer/"'
  tags: cve,wordpress,wp-plugin,td-composer,medium,production

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/td-composer/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "td-composer"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 5.0')