id: CVE-2024-5709-js_composer-7fad30c8-fd8a-4cf2-a3aa-16a374231b87

info:
  name: >
    WPBakery <= 7.7 - Authenticated (Author+) Local File Inclusion
  author: topscoder
  severity: low
  description: >
    The WPBakery Visual Composer plugin for WordPress is vulnerable to Local File Inclusion in all versions up to, and including, 7.7 via the 'layout_name' parameter. This makes it possible for authenticated attackers, with Author-level access and above, and with post permissions granted by an Administrator, to include and execute arbitrary files on the server, allowing the execution of any PHP code in those files. This can be used to bypass access controls, obtain sensitive data, or achieve code execution in cases where images and other “safe” file types can be uploaded and included.
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/7fad30c8-fd8a-4cf2-a3aa-16a374231b87?source=api-prod
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H
    cvss-score: 8.8
    cve-id: CVE-2024-5709
  metadata:
    fofa-query: "wp-content/plugins/js_composer/"
    google-query: inurl:"/wp-content/plugins/js_composer/"
    shodan-query: 'http.html:"wp-content/plugins/js_composer/"'
  tags: cve,wordpress,wp-plugin,js_composer,low,production

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/js_composer/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "js_composer"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 7.7')