id: CVE-2024-7963-cmsmasters_content_composer-42c1d2ea-dea6-4cde-8db3-37709da9eb71

info:
  name: >
    CMSMasters Content Composer <= 1.8.8 - Authenticated (Contributor+) Stored Cross-Site Scripting via Shortcode
  author: topscoder
  severity: low
  description: >
    The CMSMasters Content Composer plugin for WordPress is vulnerable to Stored Cross-Site Scripting via the plugin's multiple shortcodes in all versions up to, and including, 1.8.8 due to insufficient input sanitization and output escaping on user supplied attributes. This makes it possible for authenticated attackers, with contributor-level access and above, to inject arbitrary web scripts in pages that will execute whenever a user accesses an injected page.
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/42c1d2ea-dea6-4cde-8db3-37709da9eb71?source=api-prod
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:L/I:L/A:N
    cvss-score: 6.4
    cve-id: CVE-2024-7963
  metadata:
    fofa-query: "wp-content/plugins/cmsmasters-content-composer/"
    google-query: inurl:"/wp-content/plugins/cmsmasters-content-composer/"
    shodan-query: 'http.html:"wp-content/plugins/cmsmasters-content-composer/"'
  tags: cve,wordpress,wp-plugin,cmsmasters-content-composer,low,production

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/cmsmasters-content-composer/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "cmsmasters-content-composer"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.8.8')