id: CVE-2024-32957-live_composer_page_builder-4e8b8689-ab6a-426b-9aba-4fa14c455ff1

info:
  name: >
    Page Builder: Live Composer <= 1.5.38 - Missing Authorization
  author: topscoder
  severity: low
  description: >
    The Page Builder: Live Composer plugin for WordPress is vulnerable to unauthorized modification of data due to a missing capability check on the dslc_ajax_add_module() function in versions up to, and including, 1.5.38. This makes it possible for authenticated attackers, with author-level access and above, to add modules.
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/4e8b8689-ab6a-426b-9aba-4fa14c455ff1?source=api-prod
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:N
    cvss-score: 4.3
    cve-id: CVE-2024-32957
  metadata:
    fofa-query: "wp-content/plugins/live-composer-page-builder/"
    google-query: inurl:"/wp-content/plugins/live-composer-page-builder/"
    shodan-query: 'http.html:"wp-content/plugins/live-composer-page-builder/"'
  tags: cve,wordpress,wp-plugin,live-composer-page-builder,low,production

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/live-composer-page-builder/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "live-composer-page-builder"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.5.38')