id: CVE-2023-23681-image_hover_effects_visual_composer_extension-92ffaa23-08f2-4aa4-84c3-a84c26ed8474

info:
  name: >
    Image Hover Effects For WPBakery Page Builder <= 4.0 - Authenticated (Contributor+) Stored Cross-Site Scripting via shortcode
  author: topscoder
  severity: low
  description: >
    The Image Hover Effects For WPBakery Page Builder plugin for WordPress is vulnerable to Stored Cross-Site Scripting via the plugin's shortcode(s) in versions up to, and including, 4.0 due to insufficient input sanitization and output escaping on user supplied attributes. This makes it possible for authenticated attackers with contributor-level and above permissions to inject arbitrary web scripts in pages that will execute whenever a user accesses an injected page.
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/92ffaa23-08f2-4aa4-84c3-a84c26ed8474?source=api-prod
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:L/I:L/A:N
    cvss-score: 6.4
    cve-id: CVE-2023-23681
  metadata:
    fofa-query: "wp-content/plugins/image-hover-effects-visual-composer-extension/"
    google-query: inurl:"/wp-content/plugins/image-hover-effects-visual-composer-extension/"
    shodan-query: 'http.html:"wp-content/plugins/image-hover-effects-visual-composer-extension/"'
  tags: cve,wordpress,wp-plugin,image-hover-effects-visual-composer-extension,low,production

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/image-hover-effects-visual-composer-extension/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "image-hover-effects-visual-composer-extension"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 4.0')