id: visual-composer-starter-6909271bdc06f95eea673edff022023b

info:
  name: >
    Visual Composer Starter <= 3.3 - Authenticated (Contributor+) Stored Cross-Site Scripting
  author: topscoder
  severity: low
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/72c0fc66-44c7-4657-878a-e5109178e8e3?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/themes/visual-composer-starter/"
    google-query: inurl:"/wp-content/themes/visual-composer-starter/"
    shodan-query: 'vuln:'
  tags: cve,wordpress,wp-theme,visual-composer-starter,low

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/themes/visual-composer-starter/style.css"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Version: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Version: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "visual-composer-starter"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 3.3')