id: CVE-2025-23775-gmaps_for_visual_composer_free-2c251bf5-f6c0-4d2e-a240-95b0f1fce3f5

info:
  name: >
    GMAPS for WPBakery Page Builder Free <= 1.2 - Authenticated (Contributor+) Stored Cross-Site Scripting
  author: topscoder
  severity: low
  description: >
    The GMAPS for WPBakery Page Builder Free plugin for WordPress is vulnerable to Stored Cross-Site Scripting in versions up to, and including, 1.2 due to insufficient input sanitization and output escaping. This makes it possible for authenticated attackers, with contributor-level access and above, to inject arbitrary web scripts in pages that will execute whenever a user accesses an injected page.
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/2c251bf5-f6c0-4d2e-a240-95b0f1fce3f5?source=api-prod
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:L/I:L/A:N
    cvss-score: 6.4
    cve-id: CVE-2025-23775
  metadata:
    fofa-query: "wp-content/plugins/gmaps-for-visual-composer-free/"
    google-query: inurl:"/wp-content/plugins/gmaps-for-visual-composer-free/"
    shodan-query: 'http.html:"wp-content/plugins/gmaps-for-visual-composer-free/"'
  tags: cve,wordpress,wp-plugin,gmaps-for-visual-composer-free,low,production

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/gmaps-for-visual-composer-free/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "gmaps-for-visual-composer-free"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 1.2')