id: CVE-2025-2573-amazing_service_box_visual_composer_addons-a4f6ce4d-6ca5-4a62-ae84-9dd190fc0392

info:
  name: >
    Amazing service box Addons For WPBakery Page Builder <= 2.0.0 - Authenticated (Author+) Stored Cross-Site Scripting via SVG File Upload
  author: topscoder
  severity: low
  description: >
    The Amazing service box Addons For WPBakery Page Builder (formerly Visual Composer) plugin for WordPress is vulnerable to Stored Cross-Site Scripting via SVG File uploads in all versions up to, and including, 2.0.0 due to insufficient input sanitization and output escaping. This makes it possible for authenticated attackers, with Author-level access and above, to inject arbitrary web scripts in pages that will execute whenever a user accesses the SVG file.
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/a4f6ce4d-6ca5-4a62-ae84-9dd190fc0392?source=api-prod
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:L/I:L/A:N
    cvss-score: 6.4
    cve-id: CVE-2025-2573
  metadata:
    fofa-query: "wp-content/plugins/amazing-service-box-visual-composer-addons/"
    google-query: inurl:"/wp-content/plugins/amazing-service-box-visual-composer-addons/"
    shodan-query: 'http.html:"wp-content/plugins/amazing-service-box-visual-composer-addons/"'
  tags: cve,wordpress,wp-plugin,amazing-service-box-visual-composer-addons,low,production

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/amazing-service-box-visual-composer-addons/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag: ([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "amazing-service-box-visual-composer-addons"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 2.0.0')