id: CVE-2025-14071-live_composer_page_builder-4b15c991-5256-405c-8382-85dba6f032ba

info:
  name: >
    Live Composer – Free WordPress Website Builder <= 2.0.2 - Authenticated (Contributor+) PHP Object Injection via dslc_module_posts_output Shortcode
  author: topscoder
  severity: low
  description: >
    The Live Composer – Free WordPress Website Builder plugin for WordPress is vulnerable to PHP Object Injection in all versions up to, and including, 2.0.2 via deserialization of untrusted input in the dslc_module_posts_output shortcode. This makes it possible for authenticated attackers, with Contributor-level access and above, to inject a PHP Object. No known POP chain is present in the vulnerable plugin, which means this vulnerability has no impact unless another plugin or theme containing a POP chain is installed on the site. If a POP chain is present via an additional plugin or theme installed on the target system, it may allow the attacker to perform actions like delete arbitrary files, retrieve sensitive data, or execute code depending on the POP chain present.
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/4b15c991-5256-405c-8382-85dba6f032ba?source=api-prod
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:H/I:H/A:H
    cvss-score: 7.5
    cve-id: CVE-2025-14071
  metadata:
    fofa-query: "wp-content/plugins/live-composer-page-builder/"
    google-query: inurl:"/wp-content/plugins/live-composer-page-builder/"
    shodan-query: 'http.html:"wp-content/plugins/live-composer-page-builder/"'
  tags: cve,wordpress,wp-plugin,live-composer-page-builder,low,production

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/live-composer-page-builder/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag:\\s*([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "live-composer-page-builder"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 2.0.2')