id: CVE-2025-68598-live_composer_page_builder-3f3d6028-37ea-495d-aeb0-8f7cc940d2fd

info:
  name: >
    Page Builder: Live Composer <= 2.0.6 - Authenticated (Contributor+) Stored Cross-Site Scripting
  author: topscoder
  severity: low
  description: >
    The Page Builder: Live Composer plugin for WordPress is vulnerable to Stored Cross-Site Scripting in versions up to, and including, 2.0.6 due to insufficient input sanitization and output escaping. This makes it possible for authenticated attackers, with contributor-level access and above, to inject arbitrary web scripts in pages that will execute whenever a user accesses an injected page.
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/3f3d6028-37ea-495d-aeb0-8f7cc940d2fd?source=api-prod
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:L/I:L/A:N
    cvss-score: 6.4
    cve-id: CVE-2025-68598
  metadata:
    fofa-query: "wp-content/plugins/live-composer-page-builder/"
    google-query: inurl:"/wp-content/plugins/live-composer-page-builder/"
    shodan-query: 'http.html:"wp-content/plugins/live-composer-page-builder/"'
  tags: cve,wordpress,wp-plugin,live-composer-page-builder,low,production

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/live-composer-page-builder/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag:\\s*([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "live-composer-page-builder"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 2.0.6')