id: CVE-2025-50005-td_composer-e1012821-dae9-4fed-9f18-90eef50114ac

info:
  name: >
    tagDiv Composer <= 5.4.2 - Authenticated (Contributor+) Stored Cross-Site Scripting
  author: topscoder
  severity: low
  description: >
    The tagDiv Composer plugin for WordPress is vulnerable to Stored Cross-Site Scripting in versions up to, and including, 5.4.2 due to insufficient input sanitization and output escaping. This makes it possible for authenticated attackers, with contributor-level access and above, to inject arbitrary web scripts in pages that will execute whenever a user accesses an injected page.
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/e1012821-dae9-4fed-9f18-90eef50114ac?source=api-prod
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:L/I:L/A:N
    cvss-score: 6.4
    cve-id: CVE-2025-50005
  metadata:
    fofa-query: "wp-content/plugins/td-composer/"
    google-query: inurl:"/wp-content/plugins/td-composer/"
    shodan-query: 'http.html:"wp-content/plugins/td-composer/"'
  tags: cve,wordpress,wp-plugin,td-composer,low,production

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/td-composer/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag:\\s*([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "td-composer"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 5.4.2')