id: CVE-2026-24594-addons_for_visual_composer-dd773571-1f30-4b2b-8a0a-dde3ee1c53d9

info:
  name: >
    Livemesh Addons for WPBakery Page Builder <= 3.9.4 - Authenticated (Editor+) Stored Cross-Site Scripting
  author: topscoder
  severity: low
  description: >
    The Livemesh Addons for WPBakery Page Builder plugin for WordPress is vulnerable to Stored Cross-Site Scripting in versions up to, and including, 3.9.4 due to insufficient input sanitization and output escaping. This makes it possible for authenticated attackers, with editor-level access and above, to inject arbitrary web scripts in pages that will execute whenever a user accesses an injected page. This only affects multi-site installations and installations where unfiltered_html has been disabled.
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/dd773571-1f30-4b2b-8a0a-dde3ee1c53d9?source=api-prod
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:C/C:L/I:L/A:N
    cvss-score: 4.4
    cve-id: CVE-2026-24594
  metadata:
    fofa-query: "wp-content/plugins/addons-for-visual-composer/"
    google-query: inurl:"/wp-content/plugins/addons-for-visual-composer/"
    shodan-query: 'http.html:"wp-content/plugins/addons-for-visual-composer/"'
  tags: cve,wordpress,wp-plugin,addons-for-visual-composer,low,production

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/addons-for-visual-composer/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag:\\s*([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "addons-for-visual-composer"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 3.9.4')